
services:
  # =================================================================
  # CONFORMANCE SUITE SERVICES (profile: github-ci)
  # Used by CI to build/test conformance suite from source
  # Local development uses pre-built images via CONFORMANCE_IMAGE env var
  # =================================================================
  
  # MongoDB for conformance suite storage
  mongodb:
    image: mongo:8.0.12
    container_name: tck-mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - tck-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - github-ci

  # Conformance suite HTTPS server
  httpd:
    build:
      context: ./httpd-ci
      dockerfile: Dockerfile
    container_name: tck-httpd
    ports:
      - "8443:8443"
    networks:
      - tck-network
    depends_on:
      - conformance-suite
    profiles:
      - github-ci

  # Conformance suite server (CI builds from source, Local uses pre-built)
  conformance-suite:
    image: ${CONFORMANCE_IMAGE:-ghcr.io/descoped/oidc-conformance-suite:latest}
    container_name: tck-conformance-suite
    ports:
      - "9999:9999"  # Conformance suite API port
    environment:
      - JAVA_OPTS=-Xmx2g -XX:MaxMetaspaceSize=512m
      - BASE_URL=https://localhost.emobix.co.uk:8443
      - DEVMODE=true
      - STARTREDIR=true
    networks:
      - tck-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost.emobix.co.uk:127.0.0.1"
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    profiles:
      - github-ci

  # =================================================================
  # TCK VALIDATOR (PRIMARY SERVICE)
  # =================================================================

  # TCK Conformance Validator (isolated Python environment)
  validator:
    build:
      context: .
      dockerfile: Dockerfile.tck
    image: authly-tck:latest
    container_name: tck-validator
    volumes:
      - ./reports:/tck/reports
      - ./config:/tck/config:ro
    networks:
      - tck-network
    environment:
      - AUTHLY_BASE_URL=http://host.docker.internal:8000
      - TCK_REPORTS_DIR=/tck/reports/latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - validator  # Default profile for lightweight validation
    restart: "no"  # Run once and exit
    command: python src/validator.py

  # =================================================================
  # NETWORK CONFIGURATION  
  # =================================================================

networks:
  tck-network:
    driver: bridge
    external: false
  # Connect to external Authly network if available
  authly-network:
    external: true
    name: authly_authly-net

volumes:
  mongo_data:
    driver: local