name: Build and Test (Native)

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
    
    - name: Install dependencies
      run: |
        uv sync --all-groups
    
    - name: Run linting
      run: |
        uv run ruff check .
        uv run ruff format --check .
    
    - name: Run tests with coverage
      env:
        # Resource Manager Configuration
        AUTHLY_MODE: testing
        AUTHLY_BOOTSTRAP_ENABLED: true
        
        # Database (uses testcontainers)
        DATABASE_URL: postgresql://test:test@localhost:5432/test
        
        # JWT Configuration
        JWT_SECRET_KEY: test-secret-key-for-ci-only-256-bit-long
        JWT_REFRESH_SECRET_KEY: test-refresh-secret-key-for-ci-only-256-bit-long
        
        # Admin Configuration
        AUTHLY_ADMIN_USERNAME: admin
        AUTHLY_ADMIN_PASSWORD: admin123
        AUTHLY_ADMIN_EMAIL: admin@localhost
        AUTHLY_ADMIN_ALLOW_LOCALHOST: true
        AUTHLY_ADMIN_API_ENABLED: true
      run: |
        uv run pytest -v --tb=short --cov=src/authly --cov-report=xml --cov-report=term
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: descoped/authly

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
    
    - name: Build package
      run: |
        uv build