name: Build and Test (Native)

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'

env:
  PYTHON_VERSION: '3.11'
  UV_VERSION: '0.5.11'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ env.UV_VERSION }}
    
    - name: Install dependencies
      run: |
        uv sync --all-groups
    
    - name: Run linting
      run: |
        uv run ruff check .
        uv run ruff format --check .
    
    - name: Run tests with coverage
      env:
        AUTHLY_SECRET_KEY: test-secret-key-for-ci-only
        AUTHLY_ADMIN_USERNAME: admin
        AUTHLY_ADMIN_PASSWORD: admin123
        AUTHLY_ADMIN_EMAIL: admin@localhost
        AUTHLY_ADMIN_ALLOW_LOCALHOST: true
      run: |
        uv run pytest -v --tb=short --cov=src/authly --cov-report=xml --cov-report=term
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ env.UV_VERSION }}
    
    - name: Build package
      run: |
        uv build